---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	policy(policy)
	risk(risk)
	evaluator(evaluator)
	__end__([<p>__end__</p>]):::last
	__start__ --> policy;
	evaluator --> __end__;
	policy -.-> risk;
	policy -.-> evaluator;
	policy -.-> __end__;
	risk -.-> policy;
	risk -.-> evaluator;
	risk -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
